name=DataLogger
version=0.2.0
author=Claverie Dimitri, Peux Axel
maintainer=Claverie Dimitri <dimitri.claverie@limayrac.fr>
sentence=Systeme de journalisation sur carte SD avec rotation de fichiers.
paragraph=Permet d'enregistrer des logs (INFO, WARN, ERROR) sur une carte SD avec horodatage et gestion automatique de la taille des fichiers (rotation a 1Mo).
category=Data Storage
url=https://github.com/votre-repo/DataLogger
architectures=*